---
# File: host.yaml - these tasks ensures the hostname and related system settings are properly configured

- name: 'host | update system hostname to match inventory'
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'
  when:
  - ansible_hostname != inventory_hostname

- name: 'host | update etc hosts with cluster information'
  ansible.builtin.template:
    src: 'etc-hosts.j2'
    dest: '/etc/hosts'
    mode: 0644
