---
# File: kernel.yaml - These tasks ensure the proper kernel modules and kernel parameters are loaded

- name: 'kernel | ensure sysctl parameters are configured and loaded'
  ansible.builtin.template:
    src: 'sysctl-kubernetes.conf.j2'
    dest: '/etc/sysctl.d/99-kubernetes-sysctl.conf'
    mode: 0644
  notify: systemd-sysctl configuration changed

- name: 'kernel | ensure modules are configured at node startup'
  ansible.builtin.template:
    src: 'modules-kubernetes.conf.j2'
    dest: '/etc/modules-load.d/kubernetes-modules.conf'
    mode: 0644

- name: 'kernel | ensure kernel modules are loaded'
  community.general.modprobe:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ kernel_modules }}'
