---
- name: 'get os specific variables'
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
  - files:
    - '{{ ansible_distribution|lower|replace(" ", "_") }}.yaml'
    - '{{ ansible_os_family|lower }}-{{ ansible_architecture }}.yaml'
    - '{{ ansible_os_family|lower }}.yaml'
    skip: true

- include: 'host.yaml'

- include: 'boot.yaml'

- include: 'kernel.yaml'

- include: 'packages.yaml'

- include: 'timesyncd.yaml'

- include: 'motd.yaml'

- include: 'sshd.yaml'

- include: 'logging.yaml'

- include: 'user.yaml'
