---
# File: motd.yaml - these tasks ensure that the motd-news and related login jargon is disabled

- name: 'motd | check for motd news configuration'
  ansible.builtin.stat:
    path: '/etc/default/motd-news'
  register: motd_result

- name: 'motd | disable motd-news'
  ansible.builtin.lineinfile:
    dest: '/etc/default/motd-news'
    state: 'present'
    regexp: '^ENABLED='
    line: 'ENABLED=0'
  when: motd_result.stat.exists
