# This role configures the systemd-timesyncd service
---
# File: timesyncd.yaml - these tasks properly configure NTP and locale on every host

- name: 'timesyncd | set system timezone'
  community.general.timezone:
    name: "{{ timesyncd_timezone }}"
  notify: systemd-timesyncd configuration changed

- name: 'timesyncd | configure timesyncd'
  ansible.builtin.template:
    src: 'timesyncd.conf.j2'
    dest: '/etc/systemd/timesyncd.conf'
    backup: true
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: systemd-timesyncd configuration changed

- name: 'timesyncd | ensure timesyncd systemd service is enabled'
  ansible.builtin.service:
    name: 'systemd-timesyncd.service'
    enabled: true
    state: 'started'
