---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: mediaserver
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: radarr
      version: 10.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: linuxserver/radarr
      tag: nightly
    strategy:
      type: Recreate
    podAnnotations:
      sidecar.istio.io/inject: "true"
    additionalVolumeMounts:
    - name: media-path
      mountPath: /data
    additionalVolumes:
    - name: media-path
      persistentVolumeClaim:
        claimName: nfs-media
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - sonarr
                - plex
          weight: 100
    env:
      TZ: "America/Toronto"
      PUID: 1001
      PGID: 1001
    persistence:
      config:
        enabled: true
        mountPath: /config
        skipuninstall: true
        existingClaim: radarr-config
