---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: mediaserver
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 10.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v3.0.2.4552
    strategy:
      type: Recreate
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
      - host: radarr.milton.mcf.io
        paths:
        - path: /
          pathType: Prefix
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
    additionalVolumeMounts:
    - name: media-path
      mountPath: /data
    additionalVolumes:
    - name: media-path
      persistentVolumeClaim:
        claimName: nfs-media
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - sonarr
                - plex
          weight: 100
    env:
      TZ: "America/Toronto"
    persistence:
      config:
        enabled: true
        mountPath: /config
        skipuninstall: true
        existingClaim: radarr-config
