apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-mcfio-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:dv0ulSzezLTh/5fiizQKlkZBnnaxAHt2U1xnRcm+O0TyAPhY3mi3CA==,iv:LzuSA9/Csi4KlzN5W3lKathoUC1yruFANeO7EyMIMB4=,tag:DJBNXf5N/zmIZ7TcX7wAjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-06T13:19:33Z"
    mac: ENC[AES256_GCM,data:hFQ1UZoUk439NQrB1bVTjkNzik5D/1Iu5IbVldyoB5fuV4lqMns41kSh6dlf7bWiQKG/SUuiIbMcwer4u7EPGtxuCJxo9tvyDXgsj4zfW+teEJxdV2aLrpMPMv6TcxAQZquj/XGV1vLww/7o0YZg5gBT8fl8sn/JcuZEXNy5PiU=,iv:IaqOgEpbCK3zWS91rWPXOkiwpok3o5UNcrp1dcF5HA0=,tag:FO21ulFXK7mp1kVVUXFuMA==,type:str]
    pgp:
        - created_at: "2021-04-06T13:19:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/+Mr39iMf1wM/0cvhEHk6q2m64irw8+cAV2egECBlrdOE1
            SwrC6qP1S7ywEuQyE078UHr9+FiC73jyWBEhWvJuPkfUKaXQkEkvytFAY55dKhoF
            yVeVu/t064bfAkVCJi9WEc7aAgQ8EIPB0cBy1OyZH4/3eLokzWPZTUtIoi9kg1V+
            mppHIxI0afOydqhVasN+kNwN3DaokYxa04acX2wco+bfkkmrejzVz17O/unpQFA0
            cMNa3GK/0hrau9CEbKO8SHjr8AzxL8bvGP9AmJGTYljjXwNMBM0ShgFrIk2odLfX
            1kMQpzUx5jqDKoA1+NKopQfB5vds6WuO8TNJ/llOPugMzu4sQmbS+TecNjBfGCyh
            itQ8bUjAj/iD0vVESTn7OIr0ubF/M/+gIy3MlI1wCpk1yjXiKLjvwtK/Sd24JZwf
            wlfzHJfCPoxkLsWDJ34futJGoQVp1jT7NX9a/mEFslziUBVyqimZYfldM+sayuc3
            b8bJDTBFaLdee6fk6+qi43tNdgGv2M4yfYTg0kB3BOzuPv6BJjJDjXLSCUMWXSuO
            w3ZIrDZA0G38qHmCG0d9dLc/FBpAzzhxEgRmcs7xGUxIKLCxGnWlwy3/o2TZOiov
            9Wmde7RckW/8Zi6kK2oJCa0JkRxS29TuiSg/CW4aUkqr4ZS+9yTljUQdEGEogqzS
            VgEfEyYSM42QhUnCoRyGyhQmSqnkomNeA4AT+ILMIOUrDojLM41UZDB8Cga365I3
            7S8VCqsxiCt1MzBd3vnkwosyXJrFrIELUGyeCzVC7CxnJnDq1YIK
            =Ezf1
            -----END PGP MESSAGE-----
          fp: 14DC38072204E1AC17AB0FCA0EFB186BD4637523
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
