---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 12h
  maxHistory: 2
  chart:
    spec:
      chart: rook-ceph
      version: v1.5.4
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 5m
  values:
    csi:
      enableCephfsDriver: false
      pluginTolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 256Mi
