---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  values:
    installCRDs: false
    cleanUpCRDs: false
    initContainers:
    - name: velero-plugin-for-microsoft-azure
      image: mcfio/velero-plugin-for-microsoft-azure:v1.1.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    configuration:
      provider: azure
      backupStorageLocation:
        name: default
        bucket: velero
    backupsEnabled: true
    snapshotsEnabled: true
    deployRestic: false
