---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      version: 6.2.0
  values:
    image:
      tag: 7.3.7
    ingress:
      hosts:
      - grafana.milton.mcf.io
    grafana.ini:
      server:
        root_url: https://grafana.milton.mcf.io
