---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: milton-mcf-io-wc-cert
  namespace: istio-system
spec:
  secretName: milton-mcf-io-wc-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - milton.mcf.io
  - '*.milton.mcf.io'
