---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  hub: docker.io/querycapistio
  tag: 1.9.2-distroless

  meshConfig:
    extensionProviders:
    - name: oauth2-proxy
      envoyExtAuthzHttp:
        service: oauth2-proxy.oauth2-proxy.svc.cluster.local
        port: 80
        includeHeadersInCheck: ["authorization", "cookie"]
        headersToUpstreamOnAllow: ["authorization", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token"]
        headersToDownstreamOnDeny: ["content-type", "set-cookie"]
    accessLogFile: /dev/stdout
    enableTracing: false
    defaultConfig:
      tracing:
        zipkin:
          address: 127.0.0.1:31337
    outboundTrafficPolicy:
      mode: ALLOW_ANY

  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: false
      k8s:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
        resources:
          requests:
            cpu: 100m
            memory: 128Mi

    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
          limits:
            cpu: "1"
            memory: 128Mi
        service:
          loadBalancerIP: 192.168.45.105

  values:
    pilot:
      replicaCount: 2
      autoscaleEnabled: true
      autoscaleMin: 2
    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        replicaCount: 2
        autoscaleEnabled: true
        autoscaleMin: 2
        podAntiAffinityLabelSelector:
        - key: istio
          operator: In
          values: ingressgateway
          topologyKey: kubernetes.io/hostname
    global:
      proxy:
        autoInject: disabled
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 600m
            memory: 128Mi
      proxy_init:
        image: proxyv2
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 600m
            memory: 128Mi
      tracer:
        zipkin: ~
