---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  hub: docker.io/querycapistio
  tag: 1.9.2-distroless

  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: false
    defaultConfig:
      tracing:
        zipkin:
          address: 127.0.0.1:31337

  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: false
      k8s:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
        resources:
          requests:
            cpu: 100m
            memory: 128Mi

    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
        replicaCount: 2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        service:
          loadBalancerIP: 192.168.45.105

    pilot:
      k8s:
        hpaSpec:
          minReplicas: 2
        replicaCount: 2
        resources:
          requests:
            cpu: 500m
            memory: 1Gi

  values:
    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: true
        podAntiAffinityLabelSelector:
        - key: istio
          operator: In
          values: ingressgateway
          topologyKey: kubernetes.io/hostname
    global:
      arch:
        arm64: 2
        amd64: 2
      defaultNodeSelector:
        kubernetes.io/arch: arm64
      proxy:
        autoInject: disabled
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      proxy_init:
        image: proxyv2
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
      tracer:
        zipkin: ~
