---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  hosts:
  - zigbee.milton.mcf.io
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - route:
    - destination:
        host: zigbee2mqtt.home.svc.cluster.local
        port:
          number: 8080
