---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 12h
  maxHistory: 2
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 2.3.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  test:
    enable: false # Enable helm test
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.5
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.5
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
    prometheus:
      serviceMonitor:
        enabled: false
      prometheusRule:
        enabled: false
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.45.100-192.168.45.105
