---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/istio/istio/1.9.2/manifests/charts/istio-operator/crds/crd-operator.yaml
- deployment.yaml
