---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: mediaserver
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: overseerr
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: sctx/overseerr
      tag: 1.23.1
    podAnnotations:
      sidecar.istio.io/inject: "true"
    env:
      TZ: America/Toronto
      LOG_LEVEL: info
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config
        mountPath: /app/config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
