---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 12h
  maxHistory: 2
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki-stack
      version: 2.3.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  # Depends on having prometheus-operator due to service monitor resources.
  dependsOn:
  - name: kube-prometheus-stack
    namespace: monitoring
  valuesFrom:
  - kind: Secret
    name: loki-objectstore-config
  values:
    loki:
      config:
        schema_config:
          configs:
          - from: 2020-12-17
            store: boltdb-shipper
            object_store: azure
            schema: v11
            index:
              prefix: index_
              period: 24h
        storage_config:
          boltdb_shipper:
            active_index_directory: /data/loki/boltdb-shipper-active
            cache_location: /data/loki/boltdb-shipper-cache
            cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
            shared_store: azure
          filesystem:
            directory: /data/loki/chunks
        table_manager:
          retention_deletes_enabled: true
          retention_period: 672h
      persistence:
        enabled: true
        size: 10Gi
      serviceMonitor:
        enabled: true
      terminationGracePeriodSeconds: 60
    promtail:
      fullnameOverride: promtail
      serviceMonitor:
        enabled: true
      extraScrapeConfigs:
      - job_name: journal
        journal:
          path: /var/log/journal
          max_age: 12h
          labels:
            job: systemd-journal
        relabel_configs:
        - source_labels: ['__journal__systemd_unit']
          target_label: 'unit'
        - source_labels: ['__journal__hostname']
          target_label: 'hostname'
      extraVolumes:
      - name: journal
        hostPath:
          path: /var/log/journal
      extraVolumeMounts:
      - name: journal
        mountPath: /var/log/journal
        readOnly: true
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
