---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 12h
  maxHistory: 2
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: thanos
      version: 5.1.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: raspbernetes/thanos
      tag: v0.21.1
    objstoreConfig: |
      type: AZURE
      config:
        storage_account: ${thanos_objectstore_storage_account}
        storage_account_key: ${thanos_objectstore_storage_account_key}
        container: ${thanos_objectstore_container}
        endpoint: ""
        max_retries: 0
    query:
      enabled: true
      logFormat: json
      replicaLabels:
      - prometheus_replica
      dnsDiscovery:
        enabled: true
        sidecarsService: prom-thanos-discovery
        sidecarsNamespace: monitoring
      replicaCount: 2
      podAntiAffinityPreset: hard
      rbac:
        create: true
      autoscaling:
        enabled: false
      pdb:
        create: true
        minAvailable: 1
    queryFrontend:
      enabled: false
    bucketweb:
      enabled: true
      logFormat: json
    compactor:
      enabled: true
      logFormat: json
      retentionResolutionRaw: 10d
      retentionResolution5m: 30d
      retentionResolution1h: 90d
      strategyType: Recreate
      persistence:
        enabled: true
        accessModes:
        - ReadWriteOnce
        size: 100Gi
    storegateway:
      enabled: true
      logFormat: json
      persistence:
        enabled: false
    ruler:
      enabled: false
    receive:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
