---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 12h
  maxHistory: 2
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-charts.banzaicloud.com
      chart: thanos
      version: 0.4.3
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-stable
  values:
    objstoreSecretOverride: thanos-objectstore-config
    image:
      repository: mcfio/thanos
      tag: v0.20.1
    store:
      logFormat: json
      metrics:
        annotations:
          enabled: false
        serviceMonitor:
          enabled: true
    query:
      replicaLabels:
      - prometheus_replica
      replicaCount: 2
      logFormat: json
      podDisruptionBudget:
        enabled: true
      metrics:
        annotations:
          enabled: false
        serviceMonitor:
          enabled: true
    queryFrontend:
      enabled: false
    compact:
      enabled: true
      logFormat: json
      metrics:
        annotations:
          enabled: false
        serviceMonitor:
          enabled: true
      retentionResolutionRaw: 10d
      retentionResolution5m: 30d
      retentionResolution1h: 90d
      dataVolume:
        backend:
          persistentVolumeClaim:
            claimName: compact-data-volume
      persistentVolumeClaim:
        name: compact-data-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
    bucket:
      enabled: true
      logFormat: json
