---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: thanos-query
  namespace: monitoring
spec:
  hosts:
  - thanos.milton.mcf.io
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - route:
    - destination:
        host: thanos-query.monitoring.svc.cluster.local
        port:
          number: 9090
