---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      version: 14.2.0
  values:
    alertmanager:
      ingress:
        hosts:
        - alertmanager.milton.mcf.io
      alertmanagerSpec:
        externalUrl: https://alertmanager.milton.mcf.io
    prometheus:
      ingress:
        hosts:
        - prometheus.milton.mcf.io
      prometheusSpec:
        externalUrl: https://prometheus.milton.mcf.io
        thanos:
          image: raspbernetes/thanos:v0.17.2
