apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- etcd-client-cert.enc.yaml
- ../../../base/kube-prometheus-stack
- dashboards
patchesStrategicMerge:
- helmrelease-patch.yaml
