---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs2mqtt
  namespace: home
spec:
  dependsOn:
  - name: vernemq
    namespace: home
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zwavejs2mqtt
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: America/Toronto
      NETWORK_KEY: ${ZWAVEJS2MQTT_NETWORK_KEY}
    persistence:
      data:
        enabled: true
        skipuninstall: true
        existingClaim: zwavejs2mqtt-data
        mountPath: /usr/src/app/store
    additionalVolumeMounts:
    - name: usb
      mountPath: /dev/serial/by-id/usb-0658_0200-if00
    additionalVolumes:
    - name: usb
      hostPath:
        path: /dev/serial/by-id/usb-0658_0200-if00
    securityContext:
      privileged: true
    nodeSelector:
      feature.node.kubernetes.io/custom-zwave: "true"
