---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant-db
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector: {}
  template:
    spec:
      containers:
      - name: homeassistant-db
        image: mariadb:10.6
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: homeassistant-db-config
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: homeassistant-db-data
