---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
commonLabels:
  app.kubernetes.io/name: mysql
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: home-assistant
resources:
- pvc.yaml
- service.yaml
- secret.enc.yaml
- deployment.yaml
