---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-db
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.45.101
  externalTrafficPolicy: Local
  ports:
    - port: 3306
      name: mysql
