---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-charts.banzaicloud.com
      version: 0.3.31
  values:
    image:
      repository: raspbernetes/thanos
      tag: v0.17.2
    query:
      http:
        ingress:
          hosts:
          - thanos.milton.mcf.io
    compact:
      retentionResolutionRaw: 10d
      retentionResolution5m: 30d
      retentionResolution1h: 90d
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        disktype: ssd
    objstoreSecretOverride: thanos-objectstore-config
