apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-query-datasource
  namespace: monitoring
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: thanos
    grafana_datasource: "1"
data:
  thanos-query-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://thanos-query-http.monitoring.svc.cluster.local:10902/
      isDefault: true
