---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overseerr-cert
  namespace: mediaserver
spec:
  secretName: overseerr-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - requests.mcf.io
