---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- metallb-system
- kube-system
- cert-manager
- storage
- monitoring
- oauth2-proxy
- gitlab-system
- istio
- mediaserver
- home
- vault
