---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
  namespace: monitoring
spec:
  hosts:
  - grafana.milton.mcf.io
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - route:
    - destination:
        port:
          number: 80
        host: grafana.monitoring.svc.cluster.local
