---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs-cstor
  namespace: openebs
spec:
  interval: 6h
  maxHistory: 2
  chart:
    spec:
      chart: cstor
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: openebs-cstor
        namespace: flux-system
  values:
    csiController:
      resizer:
        image:
          registry: k8s.gcr.io/
          repository: sig-storage/csi-resizer
      snapshotter:
        image:
          registry: k8s.gcr.io/
          repository: sig-storage/csi-snapshotter
      snapshotController:
        image:
          registry: k8s.gcr.io/
          repository: sig-storage/snapshot-controller
          tag: v4.0.0
      attacher:
        image:
          registry: k8s.gcr.io/
          repository: sig-storage/csi-attacher
      provisioner:
        image:
          registry: k8s.gcr.io/
          repository: sig-storage/csi-provisioner
    cstorCSIPlugin:
    csiNode:
      driverRegistrar:
        image:
          registry: k8s.gcr.io/
          repository: sig-storage/csi-node-driver-registrar
          tag: v2.1.0
