---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.14
    env:
      TZ: "America/Toronto"
    replicas: 3
    podAnnotations:
      configmap.reloader.stakater.com/reload: "blocky-config"
    service:
      port:
        port: 4000
      additionalServices:
      - enabled: true
        nameSuffix: dns
        type: LoadBalancer
        loadBalancerIP: ${blocky_ip}
        port:
          port: 53
          name: dns-tcp
          protocol: TCP
          targetPort: 53
        additionalPorts:
        - port: 53
          name: dns-udp
          protocol: UDP
          targetPort: 53
        externalTrafficPolicy: Local
    config: |
      upstream:
        default:
        - tcp-tls:${nextdns_id}.dns1.nextdns.io
        - tcp-tls:${nextdns_id}.dns2.nextdns.io
      caching:
        minTime: 5
        maxTime: 30
        prefetching: true
      customDNS:
        mapping:
          mcf-k8s-node01.lan: 192.168.45.45
          mcf-k8s-node02.lan: 192.168.45.46
          mcf-k8s-node03.lan: 192.168.45.47
          mcf-k8s-node04.lan: 192.168.45.48
          mcf-k8s-node05.lan: 192.168.45.49
          mcf-k8s-node06.lan: 192.168.45.50
          mcf-k8s-storage01.lan: 192.168.45.51
          ca.milton.mcf.io: 192.168.30.10
          ca.mcf.io: 192.168.30.10
          dns.milton.mcf.io: 192.168.30.30
          ntp.milton.mcf.io: 192.168.30.30
          time.milton.mcf.io: 192.168.30.30
          time.mcf.io: 192.168.30.30
          ingress.milton.mcf.io: 192.168.45.105
          mqtt.milton.mcf.io: ${vernemq_ip}
          milton.mcf.io: 192.168.45.105
          kubernetes.lan: 192.168.45.40
          mcf-ca01.lan: 192.168.30.10
          mcf-k8s-cluster.milton.mcf.io: 192.168.45.40
          milton-dns1.lan: 192.168.30.30
      conditional:
        mapping:
          lan: tcp+udp:${upstream_client_lookup_ip}
      blocking:
        blackLists:
          ads:
          - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        clientGroupsBlock:
          default:
          - ads
      clientLookup:
        upstream: tcp+udp:${upstream_client_lookup_ip}
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
    prometheus:
      serviceMonitor:
        enabled: true
    nodeSelector:
      node-role.kubernetes.io/control-plane: ''
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - blocky
          topologyKey: "kubernetes.io/hostname"
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
      operator: Exists
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
