---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  maxHistory: 2
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 2.4.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.10.1
      prometheus:
        serviceMonitor:
          enabled: true
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.10.1
      prometheus:
        serviceMonitor:
          enabled: true
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
        operator: Exists
      - key: storage-node
        operator: Equal
        value: "true"
        effect: NoSchedule
    prometheusRule:
      enabled: true
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.45.100-192.168.45.105
        - 192.168.45.190-192.168.45.195
