---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 12h
  maxHistory: 2
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 2.3.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.6
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.6
      tolerations:
      - operator: Exists
        effect: NoSchedule
    prometheus:
      serviceMonitor:
        enabled: false
      prometheusRule:
        enabled: false
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.45.100-192.168.45.105
        - 192.168.45.190-192.168.45.195
