---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bazarr
  namespace: mediaserver
spec:
  hosts:
  - bazarr.milton.mcf.io
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - route:
    - destination:
        port:
          number: 6767
        host: bazarr.mediaserver.svc.cluster.local
