apiVersion: v1
kind: Secret
metadata:
    name: azure-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:gCJjETAYm8yoTa7GPd7MFkYeIdHfdYn0zyAF/bDJ51CkRiz0gSCUrNJlDYqmubBap+8M0B5ZHn/lvTZ2Na71jK76MkGMfv0Mst8jQQqMEi+7JNODi2NEOPqMpI0lxDUgrOZDzy2qZzRu2pxTfLJO6V5qZKCzdoFapQHrDXw8dB+hsVHKhHQVHdUba1cCS7QSqzRJkV2pAFkD/srIrho=,iv:eqNjg3bHWiyPGgeY8nNMgeaTen7H1xVtbIPOsgoVgAk=,tag:rYD3hOKiGhkFLb4K0bNMpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-04T20:54:12Z'
    mac: ENC[AES256_GCM,data:6eIJF8sbcueM/o3VNnJmVJ19Rz9U8vK4v1xur4ZyeQ5hoabtjFNSiY969OE4r99MrphXzSkC36h4aVrKauqzI+yYXSnInG5yqZrgXwM2hnTqxT8wHtpeJGwTSXSg84l9YUCssvezlTij081EbTcZCiGjeRX1HLgGwADFdaGvkx0=,iv:WW+leYv9IPjteTMe59t1iKC7JNeY1YtX5GHLwePc+ac=,tag:G41e4kCiOsRxlEOE1Po4nQ==,type:str]
    pgp:
    -   created_at: '2021-01-04T20:54:11Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAARAApiHve1j1w+Uorb8s+rf/hcpRSlA3uBWKy0H7MpGedqkU
            9aU3RXLvlV83eQ985ZcV/cl7k25ZDHuZYn+InStvoZUbhbZQ16vb9QSRaXWbdvIo
            PF1h2yn1du0i8oW8Xpy1As1noATCNUcB9v/yuWSGijpp/ObdceElnMvxdPp9eSHO
            EyPvZu91lQ+xwQznl152/jbtw6ngArBlW/8PLF5P+SDNoc6hU3N/CC13nmYG7xgB
            rs5WWq2EXeMPJUJ+UydfRJQF4G9TX4VtRpbL7OigM9UwYl5bT2X+eAKEyCZcxEsD
            B+HWHs7mkRVIkEaD939+mYPCLYfbtwVFroaDSyiAqj93ZecEeSWeZDhu76/Qz90e
            FXzDtt2KzjjdxLAe+a8yH8XbWF0hL61av99qYqaSndryYPayW9grtpPh0tkxY9/q
            lSiaiY6sbfwdKbnmHQ0+uSXwkpd/vFSRHFAtJQD20pquBKyJNnmMdboDMez/N0Ks
            D0lL3S7eSfMrTDNTJZQKfdbdqT5VrFSTbXOUE0429NIKV5qkb1eHYvCNZ7XVFzcX
            qlJkQkdBkNJapiJjFQ+9gJlWO0F5HSv4bdYan3ELOMm62JYkSuuRJla42ZwKNc7+
            dRw0x9HGlIE/thg0n4KDXF8GFk1vYx5y0Ut4lGdbmJ3NC7T3iPVRckLggj+stRnS
            WAHBMuXCpJHVkhHLJIhcBCAkRuhFg0lOeh4wrq3A3xx/vks/rFEBW2/HFONBQ8et
            rsGnK4FhiMZ3XsHJ2HiZ4h98IbDH6JughklNxVzAlSV2yJZZuqcvdrQ=
            =+GGG
            -----END PGP MESSAGE-----
        fp: 14DC38072204E1AC17AB0FCA0EFB186BD4637523
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
