---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 12h
  maxHistory: 2
  chart:
    spec:
      chart: rook-ceph
      version: v1.5.9
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 5m
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 256Mi
    pspEnable: false
    csi:
      enableCephfsDriver: false
      pluginTolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
    agent:
      nodeAffinity: "storage-node=true"
    discover:
      nodeAffinity: "storage-node=true"
