apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helm-release.yaml
- ceph-cluster.yaml
- ceph-block-pool.yaml
- storage-class.yaml
- virtual-service.yaml
- rook-direct-mount
- csi-snapshot-controller
- volume-snapshot-class.yaml
