---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  interval: 6h
  maxHistory: 2
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/kube-state-metrics
      chart: kube-state-metrics
      version: 2.9.7
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
  values:
    image:
      repository: raspbernetes/kube-state-metrics
