---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rclone-cache
  labels:
    app: rclone
    app.kubernetes.io/name: rclone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Gi
