---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prom-alertmanager
  namespace: monitoring
spec:
  hosts:
  - alertmanager.milton.mcf.io
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - route:
    - destination:
        host: prom-alertmanager.monitoring.svc.cluster.local
        port:
          number: 9093
