---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs-cstor
  namespace: openebs
spec:
  chart:
    spec:
      version: 2.5.0
  values:
    cvcOperator:
      componentName: cvc-operator-svc
