---

- name: 'create haproxy configuration directory'
  ansible.builtin.file:
    path: '{{ haproxy_config_dir }}'
    state: 'directory'
    mode: 0700
    owner: 'root'

- name: 'write haproxy configuration file'
  ansible.builtin.template:
    src: 'haproxy.cfg.j2'
    dest: '{{ haproxy_config_dir }}/haproxy.cfg'
    mode: 0640
    owner: 'root'
    backup: true

- name: 'get haproxy configuration file checksum'
  ansible.builtin.stat:
    path: '{{ haproxy_config_dir }}/haproxy.cfg'
    get_attributes: false
    get_checksum: true
    get_mime: false
  register: 'haproxy_cfg'

- name: 'write haproxy static pod manifest'
  ansible.builtin.template:
    src: 'haproxy.manifest.j2'
    dest: '{{ kube_manifest_dir }}/haproxy.yaml'
    mode: 0640
    owner: 'root'

- name: 'create keepalived configuration directory'
  ansible.builtin.file:
    path: '{{ keepalived_config_dir }}'
    state: 'directory'
    mode: 0700
    owner: 'root'
  when:
  - ansible_hostname in groups["control-plane"]

- name: 'write keepalived configuration file'
  ansible.builtin.template:
    src: 'keepalived.conf.j2'
    dest: '{{ keepalived_config_dir }}/keepalived.conf'
    mode: 0640
    owner: 'root'
    backup: true
  when:
  - ansible_hostname in groups["control-plane"]

- name: 'get keepalived configuration file checksum'
  ansible.builtin.stat:
    path: '{{ keepalived_config_dir }}/keepalived.conf'
    get_attributes: false
    get_checksum: true
    get_mime: false
  register: 'keepalived_conf'
  when:
  - ansible_hostname in groups["control-plane"]

- name: 'write keepalived static pod manifest'
  ansible.builtin.template:
    src: 'keepalived.manifest.j2'
    dest: '{{ kube_manifest_dir }}/keepalived.yaml'
    mode: 0640
    owner: 'root'
  when:
  - ansible_hostname in groups["control-plane"]
