---
# File: sshd.yaml - Configuration settings for SSHD

ssh_rotate_host_keys: false

ssh_modulus_min: 3071

ssh_ciphers:
- chacha20-poly1305@openssh.com
- aes256-gcm@openssh.com
- aes128-gcm@openssh.com
- aes256-ctr
- aes192-ctr
- aes128-ctr

ssh_host_keys:
- /etc/ssh/ssh_host_ed25519_key
- /etc/ssh/ssh_host_rsa_key

ssh_host_key_algorithms:
- rsa-sha2-512
- rsa-sha2-256
- ssh-ed25519
- sk-ssh-ed25519@openssh.com
- ssh-ed25519-cert-v01@openssh.com
- sk-ssh-ed25519-cert-v01@openssh.com
- rsa-sha2-256-cert-v01@openssh.com
- rsa-sha2-512-cert-v01@openssh.com

ssh_kex_algorithms:
- curve25519-sha256
- curve25519-sha256@libssh.org
- diffie-hellman-group16-sha512
- diffie-hellman-group18-sha512
- diffie-hellman-group-exchange-sha256
- diffie-hellman-group14-sha256

ssh_macs:
- hmac-sha2-256-etm@openssh.com
- hmac-sha2-512-etm@openssh.com
- umac-128-etm@openssh.com

ssh_pubkey_accepted_key_types:
- rsa-sha2-256
- rsa-sha2-512
- ssh-ed25519
- sk-ssh-ed25519@openssh.com
