---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vernemq
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vernemq.github.io/docker-vernemq
      chart: vernemq
      version: 1.6.7
      sourceRef:
        kind: HelmRepository
        name: vernemq-charts
        namespace: flux-system
      interval: 5m
  values:
    serviceMonitor:
      create: true
    service:
      type: LoadBalancer
      loadBalancerIP: ${vernemq_ip}
      mqtt:
        enabled: true
      mqtts:
        enabled: false
      ws:
        enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 1Gi
    nodeSelector:
      kubernetes.io/arch: amd64
    podAntiAffinity: hard
    persistentVolume:
      enabled: true
      size: 5Gi
    statefulset:
      annotations:
        secret.reloader.stakater.com/reload: vernemq-secrets
    secretMounts:
    - name: vernemq-auth
      secretName: vernemq-secrets
      path: /vernemq/auth
    additionalEnv:
    - name: DOCKER_VERNEMQ_ACCEPT_EULA
      value: "yes"
    - name: DOCKER_VERNEMQ_VMQ_PASSWD__PASSWORD_FILE
      value: /vernemq/auth/vmq.passwd
    # - name: DOCKER_VERNEMQ_VMQ_ACL__ACL_FILE
    #   value: /vernemq/auth/vmq.acl
