---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 12h
  maxHistory: 2
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-charts.banzaicloud.com
      chart: thanos
      version: 0.3.31
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-stable
  values:
    image:
      repository: raspbernetes/thanos
      tag: v0.17.2
    store:
      metrics:
        annotations:
          enabled: true
    query:
      replicaLabels:
      - replica
      replicaCount: 2
      logFormat: json
      podDisruptionBudget:
        enabled: true
      http:
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
          - thanos.milton.mcf.io
          tls:
          - secretName: thanos-query-tls
            hosts:
            - thanos.milton.mcf.io
      metrics:
        annotations:
          enabled: true
    compact:
      metrics:
        annotations:
          enabled: true
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        disktype: ssd
    bucket:
      enabled: true
    objstoreSecretOverride: thanos-objectstore-config
