---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: thanos
      version: 0.3.29
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-stable
        namespace: flux-system
      interval: 1m
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  values:
    image:
      repository: raspbernetes/thanos
      tag: v0.17.2
    store:
      metrics:
        serviceMonitor:
          enabled: true
    query:
      labels:
        app.kubernetes.io/workload: monitoring
      # annotations:
      #   sidecar.istio.io/inject: "true"
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
      replicaLabels:
        - replica
      metrics:
        serviceMonitor:
          enabled: true
    compact:
      metrics:
        serviceMonitor:
          enabled: true
      nodeSelector:
        disktype: ssd
    bucket:
      enabled: true
    sidecar:
      metrics:
        serviceMonitor:
          enabled: true
    objstoreSecretOverride: thanos-objectstore-config
