kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-data
  namespace: mediaserver
  labels:
    app.mcf.io/name: media-server
    app.mcf.io/component: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
