---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: mediaserver
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: plex
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.22.3.4523-d0ce30438
    env:
      TZ: "America/Toronto"
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 192.168.45.102
      externalTrafficPolicy: Local
      port:
        port: 32400
    persistence:
      config:
        enabled: true
        existingClaim: plex-data
      tmp:
        enabled: true
        emptyDir:
          enabled: true
          medium: "Memory"
    resources:
      requests:
        cpu: 500m
        memory: 250Mi
    additionalVolumeMounts:
    - name: media-path
      mountPath: /data
      readOnly: true
    additionalVolumes:
    - name: media-path
      persistentVolumeClaim:
        claimName: nfs-media
    addons:
      promtail:
        enabled: true
        image:
          repository: grafana/promtail
          tag: 2.2.1
        loki: http://loki-stack.monitoring.svc.cluster.local:3100/loki/api/v1/push
        logs:
        - name: promtail/plex
          path: "/config/Library/Application Support/Plex Media Server/Logs/*.log"
        - name: promtail/plex/plugins
          path: "/config/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/*.log"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        securityContext:
          runAsUser: 0
