---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-promtail
  namespace: mediaserver
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
    - job_name: plex-logs
      static_configs:
      - targets:
        - localhost
        labels:
          job: plex-logs
          __path__: "/plex-logs/*.log"
    - job_name: plex-plugin-logs
      static_configs:
      - targets:
        - localhost
        labels:
          job: plex-plugin-logs
          __path__: "/plex-logs/PMS Plugin Logs/*.log"
