---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      version: 2.3.1
  valuesFrom:
  - kind: Secret
    name: loki-objectstore-config
