apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    nextdns_id: ENC[AES256_GCM,data:GFL7pAHn,iv:K2Kub+LA3+0LxvBmraBTDod1mMqMlA9sDL/Xjvy3ZcY=,tag:/njb2SzP80p1NWqOngpvHw==,type:str]
    gitlab_registration_token: ENC[AES256_GCM,data:S78ULbrOfGSIojAmAbfhSfoALBU=,iv:vZxNDDXJh1f9o3p8vUVt9y6mZiWDKBhnfuthgRn+GEU=,tag:QNzCJ/H55Ddp3c0E7tYiPQ==,type:str]
    thanos_objectstore_storage_account: ENC[AES256_GCM,data:XLQivSHx7eUo6zo=,iv:0/R197m2/bbPDXUeMl0gxFEpLAGTTcALOWLrV9HWoV8=,tag:QUrvp4gklUpzxsUghcGUmw==,type:str]
    thanos_objectstore_storage_account_key: ENC[AES256_GCM,data:77KgxvZ1R+tKG3g1qDxw789tCc/JIMQoRN+yJhgo4cxPoPKtnx4O+vlgX7+oewqD5Wa8pbPRvNR+QeJShwzFHx9ImOh7RhRoUoBELbKGuHiDG0CnPq+vEw==,iv:CMLBa9KTBbjJQ24/orAtMi0Z6nWEKyFrd7BHa/675yY=,tag:v2+08XKe1xsjfU61ihqTog==,type:str]
    thanos_objectstore_container: ENC[AES256_GCM,data:QnbjoqEy8Ox8w2ET8ItHxPOL+A==,iv:FgWDpYBA5UUBgqH81H0c9XF/9NLUrYvnAgHcdp/HfJY=,tag:y7GYJx7HZSs53VcPClS47Q==,type:str]
    vault_tenant_id: ENC[AES256_GCM,data:6J5LCax8SkNi5lI5Oq/o65i4IQ/Vqw6pR+E9DVf488My8hJC,iv:Kr3K4/j77TplQwnhrt7/T44stlyj/+n0ZB4rHNlyfR0=,tag:2qTdeovRjku+RDDtK/LVyA==,type:str]
    vault_client_id: ENC[AES256_GCM,data:FEVj1EyGAKPyaRhv0v/g2VgPTkoDs20v82mndhCTEHrXa4Xw,iv:NcQkgg/xhNXz1916B22eekmt/JMDN+hkhvZrFSnjyik=,tag:E3qI//N1yh/lLuKehWnOSQ==,type:str]
    vault_client_secret: ENC[AES256_GCM,data:5A4euadv9rOvXL+/A8eWE7+eZJgMtR+H8WmiDz2X2SbOkg==,iv:eZUFVS5rHLRa8E+WumW+9pJkwtWrMtjm1RoIGDFqodc=,tag:njJucja2O6irFv+5/3ZOEQ==,type:str]
    vault_name: ENC[AES256_GCM,data:GMZs/ZRMBY0T,iv:YiVDaR6AsGLshu71hVhKSgCcFam7I5kNaJIDmtd+QTQ=,tag:bFctMK/PoQgoIPZ4L+JKHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-10T17:33:59Z"
    mac: ENC[AES256_GCM,data:PAeXXP7OZJrfFDaEZXIkztDh0mgcIZqj6N+HepAed7aPMGLCEAayD7JxCEZYR8leF7Dt2rkeZytWnfczZ/eOQzZyZ9pojqsEaUhcrOdw05had/oICHNas0BoT+0BWodu4JkzRbcL3pD4w6c/+Sy0RwHWY5+qaM6D+U4jLPF9J2I=,iv:Qtrc21eTAJkkAjMJpqXtQGc7dP9MKkH+jgQpKR2ta+0=,tag:wOiUgEyGAzM99JXoG4ff+w==,type:str]
    pgp:
        - created_at: "2021-06-10T17:33:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/9EuHRusxl9yrlcVKkLZKw6RhDEjyX1bj8iiIlTKVz5Wq2
            Ya3ilK7jG/MiMEH1Z/+1jODqUhvN1eXIoYfKBwT9bGdhJIE9i0/brrW6UdNG8EVh
            K4LbzmFrbunCP73Kfw3BA5VHUfG9IGsy9IkrAxnm9qGZQNeN2Csqwl9jxCsOz0J+
            ya8Bb+TPGSXodXmGX44aOpRkM00cW4aHwNlbkvF3HGs8h4iY6WtkwGaGZZw9e7WM
            e+xw9I4qQnQcenWTT3WGnfg7IC9aGxFvRpKwtmXJ8qq4+jeY+t97bkPPxU0o12Oq
            PpBC04e0Eg72yvMynj2ekzfRiYjIM50uYDovANajCe6F8xuUeFv7UXgulckr4lBC
            Z7ruVGpH7xGusRHkrpIcybqqZslye+3fo89qSWvux1L5ViOoXq/hH6DhURoXh+z8
            I/oUhl9wC+m2oMt05t75j3eyziwejyyV57Ht0TO4LOCQDzOPLcJ8DzZWkNRE01aL
            cxUr6/pm0V4Wez+8WXxV4nG7s96hZkBAEq6jEEJDMNYWr44BmfX9osIXPESnLSXI
            oTlZG7NEVV6lFDG6Sm3+Th2HynXnheim1W6W8a/CQHi865hyLoN5gAs3YsdZicy4
            zdDKM7D3OaP3DoAYCt/KIq1+QIkcKq/jhP/MAl3X4m3UxdlYdUkH/ELPKsuNM0XS
            WAGSj0WxB+AW5e6oQLGP3DsL0aIh09Yr+rZw/RRou4LBpZ8BuxRUg+xRCbS8+xZ/
            4IyhAT+4plLJ+NSLJtz1xVEAv1p/BYhTRIW8hLT6PO/Prsj4LYYIV5U=
            =i7lw
            -----END PGP MESSAGE-----
          fp: 14DC38072204E1AC17AB0FCA0EFB186BD4637523
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
