apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    nextdns_id: ENC[AES256_GCM,data:lI0TBv18,iv:szgmdJZVZO50k5OsMeRHlohBQuqgwElmkUejagjUNqc=,tag:IDGw/JBjkgYQOY3RZIaWsw==,type:str]
    gitlab_registration_token: ENC[AES256_GCM,data:PdGBeXsYzL38bO0iolqaS8PieYU=,iv:rR43NORJE1h6IVxEU5OjBbtP5BwhiUsVUyGpnGvErVU=,tag:b0pcUC2Qa3B3iIvfB2b0Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-09T05:22:53Z"
    mac: ENC[AES256_GCM,data:0rSeSrgoomjsRJRTGk+inRzK552emYthbILM6gYkoBquW8v93fKM4f7T/hVA7hyyBf0w4dTfULvw1GpqNr+58ZM6SdaHBhEAyK98IKeWvU2uiF7m1HLpbFGRQYOZ5Qz4sEieUNwxIhMU2C/GofmQb7oVcdYgB1KfhUAOPO25lYI=,iv:eejDzxDAEZrDbwheotDC46rBzMjVhN47JNt4nMuuCgM=,tag:BjsG6d9QPotdalVDFP7lSg==,type:str]
    pgp:
        - created_at: "2021-06-09T05:22:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ//Si7wLgM9wn7ruBWBSrQGHgOD9kXD0xUxofqux55lVp4U
            IaiSG5spsAjQ6qCbxnC80exPf7uv5ogKL1jH9QDdcHlztjcRb2iNdO1wjNGVRHyK
            5KxnkE17cAqNxGsGKfA05z4Zz0BbsfwP+d1obysb0xQu6C55YxyQtamE1wPOhRlb
            z9+l9xzMFur6rVaQcfl7BDNH70Ds92l5MrY8svMOR+u0gBXdXi6sMbcM9ym1t5Do
            IIwAIAs+CRzpz0fTOmYdUUMCbBXtWFCaS+/xqw7ljmnO7PW4dbaUXddql3uUqfW0
            7UyRF26T+YOfmKhUXNg4Srf7LbEs+Elkpo03no8Irf6n2M1zqAAUZNTLBxl4HoEI
            BazXiNuoZtZ0OBA+dx2j0kvvwzEViPMd2EX+atTmwIICi3j8LQWzowTOWYISmLFp
            u7W2enl7WXJxJBj9+vu/oT1ZJi3y5k11WmGkXksbAH+mwbFtoDaczNiiKODNCHpk
            JSFGzWzzgX+p4Q23l+zyfvPo/SzEXMYICNdzcL3r4rOLwgogYPvtJgZJ7wcjp7PJ
            qU0shIYhAfVolfAKCBNHZiZmA0NUQRaaY9iIYJtRtl7IRN2NDT+LlXeQ2j+rWzRR
            Is60BZ0quPmdyAlNhuXA9yGeKKT6Ua1HY4XtyVEKeFfGgQztWaAvj5gwyjtYITDS
            VgEB/iDUkxt5x0/XJqIWBWZGF5NzmJszg2bWb0Rsg6oKfySzmAaDMZCbXrgPUrGD
            yOofT1rrKipRrurj3Z6iVlMpk54Ecaoy7TIy6imPClBjmcEmjQGu
            =yAC0
            -----END PGP MESSAGE-----
          fp: 14DC38072204E1AC17AB0FCA0EFB186BD4637523
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
