apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    nextdns_id: ENC[AES256_GCM,data:56qvm3Mt,iv:vkDCY1WzIzt97SmzkvnNNEpDptp/1ux1U/mhizLcvjc=,tag:Y+rynjftnEiCUU+ECJRcrw==,type:str]
    gitlab_registration_token: ENC[AES256_GCM,data:nI3clMAggAXaxVyldsglzxTp+sU=,iv:YFf+GyFgZpCZ/7DYMSdyMqVGLddxs1ABS2dKHZ/FMlY=,tag:ifRWIcytBSojxFGjjTUN5Q==,type:str]
    thanos_objectstore_storage_account: ENC[AES256_GCM,data:RjfS1nvjTrYemww=,iv:KxTsa6it5ID0AnmzKMXXXMRoX9LvsxX0ZxdibhJh28U=,tag:KUiITRIXxsvpvADd3aEplw==,type:str]
    thanos_objectstore_storage_account_key: ENC[AES256_GCM,data:wVpNcDgdLW3yHSNO0CUIyG89uqVdqEKXprEWbG9g3oPCREw+ZhRYZgFWo2NJTxmEBNMl+Awj2KhnOMv+slTxmj+OudI3mHCs7ZBLGficL1dkY/oX5n/aQA==,iv:rqSW2DVe/58eCwbttNu137yWvT8pmWPiwue4Nun3F2w=,tag:8LXCFKzNIHDGeJjLpnCqkA==,type:str]
    thanos_objectstore_container: ENC[AES256_GCM,data:q+Vk884+HDfnA3fae0UDTAigDA==,iv:VOhSgDGd/KiGZ0/TIVg9ppgKUX8DolA68t+jt43CxZQ=,tag:xNPFXmGztWzVMB3In2nqGA==,type:str]
    vault_tenant_id: ENC[AES256_GCM,data:/h48SPpiVEeWRv5VTHFlIvIU5ANK0cT80itslUMPtHhgqPjC,iv:Cv2QLOKFW7abEisfLO/uGS94SF24qkntv2Sf3czdRPo=,tag:S9FjVS6fhpOe2v/r3QImsQ==,type:str]
    vault_client_id: ENC[AES256_GCM,data:PhNLy5qIlHvxSTNVeV3vP6Kbn/g7yLtSjNqrOG8mO4M9t6oI,iv:Hqvkitb8xgz/WOm/JexvvgHALQEB3c8BBoch7Jk02XE=,tag:fYCAMXktQZ1fzJkZLLRjWQ==,type:str]
    vault_client_secret: ENC[AES256_GCM,data:c1/SEFFHdjnnTMfjvyH02XnPTFKwnO8nFELn19Ypw4Hciw==,iv:LFILxgBTrq3UWWfkd/ry5kb51/TGCujhK4+VsdV0XGU=,tag:JeelIaStetP+cCrR83NfBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-10T16:40:09Z"
    mac: ENC[AES256_GCM,data:uTqDyqFZUlwyKeawPGdVDNt+S/Zg7Sj3qU2tUpyqfqr46AlUc182Zf7A0qgiIzuxS1W+ghkNpgUNBh+CqRicR3JrXofHR6y0sXEuW52hHCggFZ8y+8+AzuX/SDFdMvgpoIi2+TMnPK4T9pIvRV7J/BdpMwp7RaOd3n22j0G5J74=,iv:UoHPp8NJk0zz6nSvyLfvsDNU2vLwktrv8AZBc2zcDR4=,tag:DpjQSNSJ7Najc5RpEgqazA==,type:str]
    pgp:
        - created_at: "2021-06-10T16:40:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/+J4u9tXWk7qqgGyAYBgeqIHW1KnmpBIuX7YpJPxNf5xA6
            ajRIeuxxnILvGMEajqYpREuvtmo/XXXMJinXXQzOJ9p6uPq9hbtAz58vsRrFCQJ1
            SAEJ4F3g9OUGv/qxNm8QEpYLS1jhUkzkQYkyIb+UpLWSLLoNNJ5L/aEqVVGqiDRN
            yR71CsBNrOeQFux9hj+xkyVYOpf/7pBDx4S4vg9nh+is5vNegrf8G22uREIHkEEv
            HTFqNB49rozwWe5bRUlsup8nv9cnWtzbJ+8MKh1G/+t5f5J8FqJIuM+2qRmU1GIP
            NuvYMgG76i7QBrGjIgOmWysjd+NVpQWwhQKnzx0DuiYYEl/hMqSwh1CH2Btq6tRG
            a0tmPmHYm2AWf6LIrenngj32cKHvh4WJwENclcI+pfn97f4Ga1qqMgFXF7CurBpx
            Qr5gCXPxorMZB+5+4Fgex5TmOyVHEWq6vzFOHc7mMncReABXsASr1Neav3URfmGG
            1jxAP6UFrVjHgLk/pGKvD+MD89i3U2uj51ghsIyN/0d8FI3mLpc6sAKcUH+BeR+K
            0TVVsKiakTquMgKJWSF8nSoKC5arAx507JUDfB+tzuO4upk3zFveiM+luBMssaz/
            425xN/JrQQlFaR0hJrR1MTDrULwPCGCTq1pjDtA2DlWvAJ6tuJSrSPntm7MEa4jS
            WAFdVVlnU7hEBxm4Q0ca03ngKj2AMxgzT31L7mYxsz0ArqZPQBH0+cKi/cOmTWnf
            XPg/jFPQPWHHvLSJnMCh5Mi49ey3CpdnTNBpui0Zqvf9pJZaCUL/wsI=
            =1Iem
            -----END PGP MESSAGE-----
          fp: 14DC38072204E1AC17AB0FCA0EFB186BD4637523
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
