apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - namespace.yaml
- toolkit-components.yaml
- toolkit-servicemonitors.yaml
- cluster-secrets.enc.yaml
- cluster-vars.yaml
- helm-repositories
- notifications
patchesStrategicMerge:
- sops-keyvault-decryptor.yaml
