---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 12h
  maxHistory: 2
  chart:
    spec:
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.3.2
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: raspbernetes/kured
    updateStrategy: RollingUpdate
    configuration:
      prometheusUrl: http://prom-prometheus.monitoring:9090
      alertFilterRegexp: '^(Watchdog|CPUThrottlingHigh)$'
      startTime: 2am
      endTime: 4am
      timeZone: America/Toronto
    service:
      create: true
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
