---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 12h
  maxHistory: 2
  chart:
    spec:
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.3.1
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: raspbernetes/kured
    configuration:
      prometheusUrl: http://z-prometheus.monitoring:9090
      alertFilterRegexp: '^(Watchdog|CPUThrottlingHigh)$'
      startTime: 6am
      endTime: 8am
    service:
      create: true
    metrics:
      create: false
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
