---

hubble:
  enabled: true
  metrics:
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - http
  listenAddress: ":4244"
  relay:
    enabled: true
  ui:
    enabled: true

# Disable automatic L2 routing between nodes, normally without BGP Full mesh this is required.
autoDirectNodeRoutes: true

# Cilium leverages MetalLB's simplified BGP announcement system for service type: LoadBalancer
bgp:
  enabled: false
  announce:
    loadbalancerIP: true

containerRuntime:
  integration: containerd

# Kubernetes control plane will set the IPAM for the cluster
ipam:
  mode: kubernetes

# force features for kube-proxy replacement
kubeProxyReplacement: strict
# The IP address with port for kube-proxy replacement health check server to serve on
kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"

prometheus:
  enabled: true
  port: 8090
  # serviceMonitor CRD may not yet exist in which this parameter needs to be
  # adjusted
  serviceMonitor:
    enabled: true

operator:
  rollOutPods: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  prometheus:
    enabled: true
    # As an install task, the serviceMonitor CRD does not yet exist
    serviceMonitor:
      enabled: true

# Kubernetes exports KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT with a ClusterIP
# of the kube-apiserver service to the pod, however without kube-proxy in this setup the Cillium
# agent needs to be made aware of how to reach the kube-apiserver
k8sServiceHost: 192.168.45.40
k8sServicePort: 8443

# Disables network encapsulation and enables packet forwarding mode.
tunnel: disabled

# Configures the CIDR used for native routing. This will disable masquerading
# of IP destinations to this subnet.
nativeRoutingCIDR: 192.168.45.0/24

# sets the maglev hash seed and table size, this avoids using the built-in seed
# tableSize value is sufficient for approx. 10 backends.
maglev:
  tableSize: 1021
  hashSeed: "P9jc887+zv7eNcUr"

loadBalancer:
  # BPF load balancing algorithm
  algorithm: maglev
  # BPF load balancing mode
  mode: dsr
