---
# Cluster Variables
cluster_name: mcf-k8s-cluster
cluster_domain: milton.mcf.io
cluster_fqdn: "{{ cluster_name }}.{{ cluster_domain }}"
cert_extra_sans:
  - "{{ apiserver_address }}"
  - "{{ cluster_fqdn }}"
kubernetes_version: "1.20.0"
authorization_mode: "Node,RBAC"
enable_admission_plugins: "NodeRestriction,AlwaysPullImages"
image_repository: k8s.gcr.io
service_subnet: "10.96.0.0/12"
pod_subnet: "10.244.0.0/16"
cgroup_driver: systemd
apiserver_address: "192.168.45.40"
apiserver_port: "8443"
enable_kube_proxy: false
enable_cgroup_v2: true
init_extra_opts: "--skip-phases=addon/kube-proxy"

# Internal loadbalancer for apiservers
loadbalancer_apiserver_port: 8443
loadbalancer_apiserver_healthcheck_port: 8081

# Enable or disable control-plane node scheduling, by default control-plane is tained as 'NoSchedule'
control_plane_scheduling: false

# Container Runtime Interface variables, additional variables can be found in roles/kubernetes/pre-flight/defaults/main.yml
cri_plugin: containerd
cri_cgroup_driver: systemd

# Container Network Interface variables
cni_plugin: cilium
