---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.gitlab.io
      chart: gitlab-runner
      version: 0.29.0
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 5m
  values:
    gitlabUrl: https://gitlab.com
    runnerRegistrationToken: ${gitlab_registration_token}
    unregisterRunners: true
    rbac:
      create: true
    runners:
      config: |
        [[runners]]
          [runners.kubernetes]
            image = "alpine:3.13"
      tags: "aarch64,arm64,mcfaul-cloud,mcfio"
    nodeSelector:
      kubernetes.io/arch: amd64
