---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: home-assistant
  namespace: home
spec:
  hosts:
  - hassio.local
  location: MESH_EXTERNAL
  ports:
  - number: 8123
    name: http
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 192.168.30.5
    ports:
      http: 8123
