---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home
  labels:
    app.mcf.io/name: home-assistant
    app.mcf.io/component: hassio
spec:
  ports:
  - name: http-web
    port: 8123
---
apiVersion: v1
kind: Endpoints
metadata:
  name: home-assistant
  namespace: home
  labels:
    app.mcf.io/name: home-assistant
    app.mcf.io/component: hassio
subsets:
- addresses:
  - ip: 192.168.30.5
  ports:
  - port: 8123
    name: http-web
