---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: external-dns
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  # Depends on prometheus-operator due to service monitor resources.
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    image:
      registry: docker.io
      repository: raspbernetes/external-dns
      tag: v0.7.4
      pullPolicy: IfNotPresent
    provider: cloudflare
    replicas: 1
    rbac:
      create: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
    crd:
      create: true
    sources:
      - ingress
      - istio-virtualservice
    domainFilters:
      - milton.mcf.io
    zoneIdFilters:
      - 73816e78e046d700ba68abfa82efd565
    cloudflare:
      secretName: cloudflare-mcfio-api-token
      email: n@mcf.io
      proxied: false
